### ISSUE TITLE
NPE at ApnsClient.operationComplete()

### ISSUE THREAD

**Issue by neyron91** [relayrides/pushy#228]
Hi! I've got an exceptions sometimes when I tried to connect to the APNs and it wasn't available:
```
[nioEventLoopGroup-2-1] INFO com.relayrides.pushy.apns.ApnsClient - Failed to connect.
java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.
	at com.relayrides.pushy.apns.ApnsClient$3.operationComplete(ApnsClient.java:444)
	at com.relayrides.pushy.apns.ApnsClient$3.operationComplete(ApnsClient.java:438)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:567)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:406)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1021)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:665)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:643)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:587)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1218)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeCloseNow(ChannelHandlerInvokerUtil.java:133)
	at io.netty.channel.DefaultChannelHandlerInvoker$13.run(DefaultChannelHandlerInvoker.java:291)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```
```
[nioEventLoopGroup-2-1] WARN io.netty.util.concurrent.DefaultPromise - An exception was thrown by com.relayrides.pushy.apns.ApnsClient$2.operationComplete()
java.lang.NullPointerException
	at com.relayrides.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:433)
	at com.relayrides.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:427)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise$3.run(DefaultPromise.java:664)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

is it a bug?

Thanks.

**Comment by jchambers** [comment]
> is it a bug?

Yes.

**Comment by jchambers** [comment]
It looks like the problem was that we had two separate listeners that could detection failure; in some cases, the "channel has closed" listener would fire before the "connection attempt failed" listener. The former would clear the "connection attempt is done" promise, and then the latter would try to mark that (now-`null`) promise as failed.

Rather than trying to find a way to force those things to happen in order, we can just eliminate the "connection attempt failed" listener since the "connection closed" listener will fire in all cases when the connection attempt would have failed.

**Comment by mobilesoftsmith** [comment]
I am using 0.5.2. It looks like this issue still exists:
[nioEventLoopGroup-2-1] INFO com.relayrides.pushy.apns.ApnsClient - Failed to connect.
java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.
	at com.relayrides.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:495)
	at com.relayrides.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:489)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:568)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:407)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1042)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:679)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:657)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:601)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1416)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeCloseNow(ChannelHandlerInvokerUtil.java:133)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeClose(DefaultChannelHandlerInvoker.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:226)
	at io.netty.handler.ssl.SslHandler$8.operationComplete(SslHandler.java:1432)
	at io.netty.handler.ssl.SslHandler$8.operationComplete(SslHandler.java:1418)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
	at io.netty.util.concurrent.DefaultPromise.notifyLateListener(DefaultPromise.java:624)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:139)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
	at io.netty.handler.ssl.SslHandler.safeClose(SslHandler.java:1418)
	at io.netty.handler.ssl.SslHandler.closeOutboundAndChannel(SslHandler.java:1243)
	at io.netty.handler.ssl.SslHandler.close(SslHandler.java:459)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeCloseNow(ChannelHandlerInvokerUtil.java:133)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeClose(DefaultChannelHandlerInvoker.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:226)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:185)
	at io.netty.handler.ssl.ApplicationProtocolNegotiationHandler.handshakeFailure(ApplicationProtocolNegotiationHandler.java:124)
	at com.relayrides.pushy.apns.ApnsClient$1$1.handshakeFailure(ApnsClient.java:411)
	at io.netty.handler.ssl.ApplicationProtocolNegotiationHandler.userEventTriggered(ApplicationProtocolNegotiationHandler.java:102)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeUserEventTriggeredNow(ChannelHandlerInvokerUtil.java:75)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeUserEventTriggered(DefaultChannelHandlerInvoker.java:136)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:138)
	at io.netty.handler.ssl.SslUtils.notifyHandshakeFailure(SslUtils.java:121)
	at io.netty.handler.ssl.SslHandler.notifyHandshakeFailure(SslHandler.java:1222)
	at io.netty.handler.ssl.SslHandler.access$700(SslHandler.java:166)
	at io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:1365)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Tue Mar 29 20:53:28 PDT 2016: Failed to send apple push notification: com.relayrides.pushy.apns.ClientNotConnectedException

**Comment by hardersen** [comment]
I'm also seeing a similar problem on 0.6.0:

```
13:57:22.348 INFO  [c.r.pushy.apns.ApnsClient] - OpenSSL (via netty-tcnative) not available; will use JDK SSL provider.
13:57:22.843 WARN  [c.r.pushy.apns.ApnsClient] - Asked for socket channel class to work with null event loop group, returning NioSocketChannel class.
13:57:33.265 WARN  [i.n.h.s.ApplicationProtocolNegotiationHandler] - [id: 0x25507704, L:/10.0.3.11:35280 - R:api.development.push.apple.com/17.172.238.203:443] TLS handshake failed:
javax.net.ssl.SSLException: handshake timed out
13:57:33.294 INFO  [c.r.pushy.apns.ApnsClient] - Failed to connect.
java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.
	at com.relayrides.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:635)
	at com.relayrides.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:629)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:568)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:407)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1064)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:689)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:667)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:611)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1416)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeCloseNow(ChannelHandlerInvokerUtil.java:133)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeClose(DefaultChannelHandlerInvoker.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:226)
	at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:71)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeCloseNow(ChannelHandlerInvokerUtil.java:133)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeClose(DefaultChannelHandlerInvoker.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:226)
	at io.netty.handler.ssl.SslHandler$8.operationComplete(SslHandler.java:1429)
	at io.netty.handler.ssl.SslHandler$8.operationComplete(SslHandler.java:1415)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
	at io.netty.util.concurrent.DefaultPromise.notifyLateListener(DefaultPromise.java:624)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:139)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
	at io.netty.handler.ssl.SslHandler.safeClose(SslHandler.java:1415)
	at io.netty.handler.ssl.SslHandler.closeOutboundAndChannel(SslHandler.java:1243)
	at io.netty.handler.ssl.SslHandler.close(SslHandler.java:459)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeCloseNow(ChannelHandlerInvokerUtil.java:133)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeClose(DefaultChannelHandlerInvoker.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:226)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:185)
	at io.netty.handler.ssl.ApplicationProtocolNegotiationHandler.handshakeFailure(ApplicationProtocolNegotiationHandler.java:124)
	at com.relayrides.pushy.apns.ApnsClient$1$1.handshakeFailure(ApnsClient.java:456)
	at io.netty.handler.ssl.ApplicationProtocolNegotiationHandler.userEventTriggered(ApplicationProtocolNegotiationHandler.java:102)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeUserEventTriggeredNow(ChannelHandlerInvokerUtil.java:75)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeUserEventTriggered(DefaultChannelHandlerInvoker.java:136)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:138)
	at io.netty.handler.ssl.SslUtils.notifyHandshakeFailure(SslUtils.java:124)
	at io.netty.handler.ssl.SslHandler.notifyHandshakeFailure(SslHandler.java:1222)
	at io.netty.handler.ssl.SslHandler.access$700(SslHandler.java:166)
	at io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:1362)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

This does not always happen. Restarting this particular instance gave:

```
14:14:09.468 INFO  [c.r.pushy.apns.ApnsClient] - OpenSSL (via netty-tcnative) not available; will use JDK SSL provider.
14:14:09.926 WARN  [c.r.pushy.apns.ApnsClient] - Asked for socket channel class to work with null event loop group, returning NioSocketChannel class.
14:14:11.377 INFO  [c.r.pushy.apns.ApnsClient] - Connected to api.development.push.apple.com/17.172.238.203:443.
```

**Comment by jchambers** [comment]
Oops—meant to reopen this. Sorry!

**Comment by jchambers** [comment]
On closer inspection, I think this should have been fixed in #261. I also added some extra protection against future `NullPointerException`s in 9e06c3a. I'm going to re-close this one for now with the expectation that we'll be putting out a point release shortly. If this happens again in or after 0.6.1, we'll reopen.

Thanks for the detailed reports, everybody!

**Comment by hardersen** [comment]
Still seeing this using 0.6.1, seems to happen some times on when the SSL handshake times out:

```
10:49:00.189 INFO  [c.r.pushy.apns.ApnsClient] - OpenSSL (via netty-tcnative) not available; will use JDK SSL provider.
10:49:00.958 WARN  [c.r.pushy.apns.ApnsClient] - Asked for socket channel class to work with null event loop group, returning NioSocketChannel class.
Caused by: java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.
	at com.relayrides.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:640)
	at com.relayrides.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:632)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:568)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:407)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1064)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:689)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:667)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:611)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1416)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeCloseNow(ChannelHandlerInvokerUtil.java:133)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeClose(DefaultChannelHandlerInvoker.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:226)
	at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:71)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeCloseNow(ChannelHandlerInvokerUtil.java:133)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeClose(DefaultChannelHandlerInvoker.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:226)
	at io.netty.handler.ssl.SslHandler.closeOutboundAndChannel(SslHandler.java:1250)
	at io.netty.handler.ssl.SslHandler.close(SslHandler.java:459)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeCloseNow(ChannelHandlerInvokerUtil.java:133)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeClose(DefaultChannelHandlerInvoker.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:226)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:185)
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:1119)
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:224)
	at io.netty.channel.ChannelFutureListener$2.operationComplete(ChannelFutureListener.java:56)
	at io.netty.channel.ChannelFutureListener$2.operationComplete(ChannelFutureListener.java:52)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:564)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:425)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:222)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:373)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	... 1 common frames omitted
```

**Comment by jchambers** [comment]
Okay. Thanks for the update. Re-opening.

**Comment by hardersen** [comment]
No problem, thank you!

FYI api.development.push.apple.com really seems to be struggling today possibly making this easier to reproduce.

**Comment by jchambers** [comment]
> api.development.push.apple.com really seems to be struggling today possibly making this easier to reproduce.

Oh—great ;)

Taking a closer look at the stack trace, I'm a little confused. I see the `caused by` part of the stack trace, but I'm not clear on what's being caused. Is there a `NullPointerException` in here somewhere? What, exactly, is dumping this stack trace?

If the problem is just that the connection future is failing with an `IllegalStateException`, that's definitely expected behavior; is there an NPE still happening that's just not showing up in the logs here?

**Comment by hardersen** [comment]
I believe the NPE is gone, only seeing IllegalStateException with "Channel closed before HTTP/2 preface completed" in the logs I have. Think I've seen slightly different stack traces earlier today, but I've cleared these logs and now api.development.push.apple.com is up again.

I believe this should be closed after all. Sorry for the false report!

**Comment by jchambers** [comment]
No worries! Thanks for checking on it!

**Comment by yaogdu** [comment]
i got that exception with the latest version

**Comment by jchambers** [comment]
> i got that exception with the latest version

Please be more specific. What were you doing when this happened? By "the latest version," do you mean 0.7.2, or a snapshot from `master`? Is this the same problem you [shared on the mailing list](https://groups.google.com/d/msg/pushy-apns/JKn3hfuea4M/trLEm0qtAwAJ)?

**Comment by yaogdu** [comment]
> Please be more specific. What were you doing when this happened? By "the latest version," do you mean 0.7.2, or a snapshot from master? Is this the same problem you shared on the mailing list?

@jchambers sorry.  It's version 0.7.2 from maven repository. when I was trying to reconnect to APNs ,it raised that error. the problem on the mailing list was posted by me.

**Comment by zhangmuxi** [comment]
@jchambers We still find this issue in version 0.8.1

`2016-12-03 22:13:51.663  INFO 1 --- [ntLoopGroup-3-1] com.relayrides.pushy.apns.ApnsClient     : Failed to connect.

java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.
	at com.relayrides.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:412)
	at com.relayrides.pushy.apns.ApnsClient$2.operationComplete(ApnsClient.java:404)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1058)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:686)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:664)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:607)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:634)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:618)
	at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:71)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:634)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:618)
	at io.netty.handler.ssl.SslHandler$8.operationComplete(SslHandler.java:1437)
	at io.netty.handler.ssl.SslHandler$8.operationComplete(SslHandler.java:1428)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:170)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
	at io.netty.handler.ssl.SslHandler.safeClose(SslHandler.java:1428)
	at io.netty.handler.ssl.SslHandler.closeOutboundAndChannel(SslHandler.java:1259)
	at io.netty.handler.ssl.SslHandler.close(SslHandler.java:449)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:634)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:618)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:475)
	at io.netty.handler.ssl.ApplicationProtocolNegotiationHandler.exceptionCaught(ApplicationProtocolNegotiationHandler.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:274)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:266)
	at io.netty.handler.ssl.SslHandler.exceptionCaught(SslHandler.java:743)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:274)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:266)
	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:78)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:274)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:266)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1301)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:274)
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:914)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:99)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:140)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by jchambers** [comment]
So this issue was originally about `NullPointerExceptions`, which were definitely a problem. Recent reports have all been about "Channel closed before HTTP/2 preface completed," which is *an entirely different issue*. As near as I can tell, there have been no recurrences of the `NullPointerException`, but please let me know if that's inaccurate.

"Channel closed before HTTP/2 preface completed" is disappointing, but it's also an expected failure mode. Connections will sometimes fail, and this is what we'd expect to see.

If you think this is something other than a transient failure that can be resolved by retrying, please provide additional details about what you were trying to do and under what conditions (APNs environment, Java version, ALPN strategy, OS, etc.).

Thanks!

**Comment by jmason** [comment]
I've seen "Channel closed before HTTP/2 preface completed" when the SSL cert is invalid, expired, or otherwise non-functional....

**Comment by jchambers** [comment]
Thanks!

It may be that we still have an issue with exception-clobbering, but let's investigate that as a separate issue.
