### ISSUE TITLE
pushy0.5.2 java.lang.NoSuchMethodError: org.apache.tomcat.jni.SSLContext.getMode(J)I

### ISSUE THREAD

**Issue by dxp558** [relayrides/pushy#242]
I created the connection using pushy0.5.1，and it worked.But using pushy0.5.2 , An exception has occurred.
I think the exception is caused by netty netty4.1.0.CR2 
pom.xml:

```xml
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-tcnative</artifactId>
    <version>1.1.33.Fork9</version>
    <classifier>osx-x86_64</classifier>
</dependency>
```

Exception:
```
2016-02-19 15:43:41.452  INFO (ApnsClient.java:332) - OpenSSL (via netty-tcnative) is available and supports ALPN; will use OpenSSL.
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.tomcat.jni.SSLContext.getMode(J)I
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:202)
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:134)
	at io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:274)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:743)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:319)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithCertificateAndPrivateKey(ApnsClient.java:324)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12InputStream(ApnsClient.java:318)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12File(ApnsClient.java:295)
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:206)
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:183)
	at pushytest.App.connect(App.java:28)
	at pushytest.App.main(App.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by jchambers** [comment]
It sounds like you need to use a newer(?) version of `netty-tcnative`. Sounds like somebody else had the same issue here: https://github.com/netty/netty/issues/4840

**Comment by kduhyun** [comment]
@dxp558  I fixed it like this.  
pom.xml:

	<properties>
		<tcnative.classifier>linux-x86_64</tcnative.classifier>
	</properties>

		<dependency>
			<groupId>com.relayrides</groupId>
			<artifactId>pushy</artifactId>
			<version>0.5.2</version>
		</dependency>
		
				
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-codec-http2</artifactId>
			<version>4.1.0.CR3</version>
			<scope>compile</scope>
		</dependency>
		
		
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-tcnative</artifactId>
			<version>1.1.33.Fork14</version>
			<classifier>${tcnative.classifier}</classifier>
		</dependency>

**Comment by jchambers** [comment]
For what it's worth, we also updated to CR3 in 10d788a. I'm going to go ahead and call this issue resolved. @dxp558 please let us know if problems persist after updating.
