### ISSUE TITLE
More accurately report handshake failures

### ISSUE THREAD

**Issue by jchambers** [relayrides/pushy#412]
A lot of bug reports come from people running into "connection closed before handshake completed" exceptions. These are absolutely normal, but also almost always have a more specific root cause—a bad certificate or a transient network outage or something. I'd like to find a way to more reliably report the root cause instead of a generic "something went wrong" message.

**Comment by jchambers** [comment]
Fixed in 01540ba.

**Comment by deepakbisht** [comment]
I am still getting this error

DefaultChannelPromise@3a9ed926(failure: java.lang.IllegalStateException: Channel closed before HTTP/2 preface completed.)

Using latest maven dependency for TURO.

**Comment by jchambers** [comment]
That's still expected sometimes; we're always striving to provide the best information possible, but sometimes "the connection closed unexpectedly" is all we know.
